function Get-CyberArkAccountDetails{
<#
.SYNOPSIS
Function to retrieve details of an account stored in the CyberArk Vault.
.DESCRIPTION
Function to retrieve details of an account stored in the CyberArk Vault. This CmdLet will only retireve the full details of one account, even if multiple accounts are found by the Vault search function.
.EXAMPLE
Get-CyberArkAccountDetails -Target components.cyber.internal -AuthenticationToken abc123 -
.PARAMETER target
The computer hostname of the PVWA hosting the CyberArk Rest API.
.PARAMETER AuthenticationToken
Authentication token generated by the Connect-CyberArkUser functon after the user has authenticated to the PVWA.
.PARAMETER Keywords
Keywords to be used when searching the Vault for account details
.PARAMETER SafeName
Name of the Safe to be searched
#>
param(
  [parameter(Mandatory=$true)][string]$Target,
  [parameter(Mandatory=$true)][string]$AuthenticationToken,
  [string]$Keywords,
  [string]$SafeName
)

PROCESS{

  $result = Invoke-RestMethod -Uri "https://$target/PasswordVault/WebServices/PIMServices.svc/Accounts?Keywords=$Keywords&Safe=$Safe" -Method Get -ContentType "application/json" -Headers @{Authorization=$AuthenticationToken} -ErrorAction Continue

  write-verbose $result

  #$result = ConvertFrom-JSON $result

  write-output $result.accounts
}

}
